apiVersion: v2
type: application
name: cert-manager
version: 0.0.0
appVersion: 0.0.0
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.1.0
    condition: cert-manager.enabled
